[package]
name = "rs-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
image = "0.25.8"
minifb = "0.28.0"
obj = "0.10.2"
parking_lot = "0.12.4"
rand = "0.9.2"
rayon = "1.11.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tobj = "4.0.3"
